name: finnhub_api
description: "A Dart package for interacting with the Finnhub API"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15
  bloc_test: ^10.0.0
